name: Build Darkmoon for Flint 4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Darkmoon
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: aarch64_cortex-a53-21.02
          PACKAGES: darkmoon
          IGNORE_ERRORS: 0

      - name: Collect Package
        run: |
          mkdir -p dist
          find bin/packages/ -type f -name "*darkmoon*.ipk" -exec cp {} dist/ \;

      - name: Upload Darkmoon IPK
        uses: actions/upload-artifact@v4
        with:
          name: darkmoon-flint4-openwrt21
          path: dist/*
